# Site settings
title: Roadrunner
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Description will go here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username: jekyll
source: src

# Build settings
markdown: kramdown

kramdown:
  input: GFM

destination: ./_site

collections:
  getting-started:
    output: true
    permalink: /:collection/:path/index.html
  design:
    output: true
    permalink: /:collection/:path/index.html
  content:
    output: true
    permalink: /:collection/:path/index.html
  feedback:
    output: true
    permalink: /:collection/:path/index.html