# Site settings
title: Roadrunner
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Roadrunner was created by designers and developers of the Digital Services at the VA to standardize our projects, scale our teams and accelerate delivery. For any feedback, please create an issue on our GitHub repository.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username: jekyll

repourl: "https://github.com/department-of-veterans-affairs/roadrunner/"

# Build settings
markdown: kramdown

destination: ./_site

collections:
  design:
    output: true
    permalink: /:collection/:path/index.html
  content:
    output: true
    permalink: /:collection/:path/index.html
  feedback:
    output: true
    permalink: /:collection/:path/index.html